### ISSUE TITLE
Error: unknown type: container

### ISSUE THREAD

**Issue by ngallo** [ofek/hatch-containers#16]
Hi,
I have installed hatch-containers

```
pip install hatch-containers
```

however after running ` hatch  run mycmd` I get and error message saying I am using un unknown type.

```
❯ hatch  run mycmd
Environment `default` has unknown type: container
```

Any idea about how to fix this?

**Comment by aleexaandr** [comment]
try `pip install hatch-containers`. also you can add it to 
```
[tool.hatch.env]
requires = ["hatch-containers"]
```
this will auto install it to root env that hatch itself is run in
