### ISSUE TITLE
status of this project?

### ISSUE THREAD

**Issue by omercnet** [ofek/hatch-containers#21]
is this project being maintained ? @ofek 
I appreciate all the hard work so far, there's great potential here and already a few open PRs

hoping to get some feedback here if you're able to maintain this or we should fork to continue development

**Comment by ofek** [comment]
Please tell me what you need merged and I can prioritize reviews

**Comment by omercnet** [comment]
thanks for the quick response!

see https://github.com/ofek/hatch-containers/pull/15 and I'll open a PR soon to provide a custom dockerfile
